"""Add Index

Revision ID: 3febbb6319ed
Revises: 5609c703ce15
Create Date: 2016-06-28 07:51:00.877097

"""

# revision identifiers, used by Alembic.
revision = '3febbb6319ed'
down_revision = '5609c703ce15'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    ### end Alembic commands ###
