"""Add playing table

Revision ID: 6cb6373ad91b
Revises: 3febbb6319ed
Create Date: 2016-07-05 18:32:09.706968

"""

# revision identifiers, used by Alembic.
revision = '6cb6373ad91b'
down_revision = '3febbb6319ed'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('playing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('since', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('playing')
    ### end Alembic commands ###
