"""create_date

Revision ID: f04c63b52c8e
Revises: 6cb6373ad91b
Create Date: 2016-11-03 18:26:44.394912

"""

# revision identifiers, used by Alembic.
revision = 'f04c63b52c8e'
down_revision = '6cb6373ad91b'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('logins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_logins_username'), 'logins', ['username'], unique=False)
    op.add_column('users', sa.Column('created', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'created')
    op.add_column('playing', sa.Column('record', sa.VARCHAR(), nullable=True))
    op.drop_index(op.f('ix_logins_username'), table_name='logins')
    op.drop_table('logins')
    ### end Alembic commands ###
